# Generated by Django 5.2.8 on 2026-08-26 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_orders', '0001_initial'),
        ('quotations', '0003_quotation_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='quotations.quotation'),
        ),
    ]
