# Generated by Django 5.2.8 on 2026-08-26 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_orders', '0002_productionorder_quotation'),
        ('quotations', '0003_quotation_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='bundles',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='marketer_name',
            field=models.CharField(blank=True, default="MD's Customer", max_length=255),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='meter_run',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='quotations.quotation'),
        ),
    ]
